# Generated by Django 4.0.2 on 2022-02-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This in a test description tarsjdfjaldjfashdfgasdfjasjfklhajghlajfdljf jadsjfads ajsdfj a'),
            preserve_default=False,
        ),
    ]
