# Generated by Django 4.0.2 on 2022-03-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='phone_number',
            field=models.CharField(default=1234567890, max_length=13),
        ),
    ]
