# Generated by Django 4.0.2 on 2022-03-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_billingaddress_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
