# Generated by Django 4.0.2 on 2022-03-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Shirt', 'Shirt'), ('Outwear', 'Outwear'), ('Sport wear', 'Sport wear'), ('Casual', 'Casual')], max_length=100),
        ),
    ]
